#!/bin/sh

export BAT_THEME="OneHalfDark"

export PATH="$HOME/.local/bin":$PATH

# Go
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# kit
export PATH="$PATH:/Users/nadeemkhedr/.kenv/bin"
export PATH="$PATH:/Users/nadeemkhedr/.kit/bin"

# zsh-history-substring-search
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="fg=green"
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="fg=red"

# similar to nvm
eval "$(fnm env)"
. /usr/local/etc/profile.d/z.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
