#!/bin/sh

export BAT_THEME="OneHalfDark"

export PATH="$HOME/.local/bin":$PATH

# Go
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"


# kit
export PATH="$PATH:/Users/nadeemkhedr/.kenv/bin"

# Karabiner 
export GOKU_EDN_CONFIG_FILE="/Users/nadeemkhedr/work/karabiner/karabiner.edn"

# similar to nvm
eval "$(fnm env)"
. /usr/local/etc/profile.d/z.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
