#!/bin/sh

# Obsidian
alias oo='cd ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Mind'
alias or='nvim ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Mind/inbox/*.md'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias k="kubectl"
alias path='echo -e ${PATH//:/\\n}'

# confirm before overwriting something
alias trash='rm -i'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

alias j="jump"
alias mux="tmuxinator"

alias starttest='for i in $(seq 1 10); do /usr/bin/time $SHELL -i -c exit; done'

# Add git root command
git config --global alias.root 'rev-parse --show-toplevel'

alias nvim-lazy="NVIM_APPNAME=LazyVim nvim"
alias nvim-kick="NVIM_APPNAME=kickstart nvim"
alias fvim="NVIM_APPNAME=LazyVim nvim"

# up and down commands for  zsh-users/zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
