#!/bin/sh

alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias k="kubectl"
alias path='echo -e ${PATH//:/\\n}'

# confirm before overwriting something
alias trash='rm -i'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

alias yoink="open -a Yoink"
alias mongostart="mongod --config /usr/local/etc/mongod.conf"
alias j="jump"
alias mux="tmuxinator"

# rg search hidden by default
alias rg="rg --hidden --glob '!.git'"

# easier to read disk
alias df='df -h' # human-readable sizes

# Add git root command
git config --global alias.root 'rev-parse --show-toplevel'

# alias nvim="lvim"
case "$(uname -s)" in

  Darwin)
    # echo 'Mac OS X'
    alias ls='ls -G'
    ;;

  Linux)
    alias ls='ls --color=auto'
    ;;

  CYGWIN* | MINGW32* | MSYS* | MINGW*)
    # echo 'MS Windows'
    ;;
  *)
    # echo 'Other OS'
    ;;
esac
