#!/bin/sh
. "$HOME/.cargo/env"

# export PATH="$PATH:/opt/homebrew/bin"
# export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";

export BAT_THEME="OneHalfDark"

export PATH="$HOME/.local/bin:$PATH"

# python
export PATH="/opt/homebrew/opt/python@3.12/libexec/bin:$PATH"

# Go
export PATH="$HOME/.local/share/go/bin:$PATH"
export GOPATH="$HOME/.local/share/go"

# broot
# source /Users/nadeemkhedr/.config/broot/launcher/bash/br

# kit
export PATH="$PATH:/Users/$USER/.kenv/bin"
export PATH="$PATH:/Users/$USER/.kit/bin"

# krew
export PATH="${PATH}:${HOME}/.krew/bin"

# zsh-history-substring-search
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="fg=green"
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="fg=red"

# similar to nvm
eval "$(fnm env)"

# enable z
eval "$(zoxide init zsh)"

# . /usr/local/etc/profile.d/z.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
