#!/bin/sh

# Listing of processing listening on some port
listening() {
    if [ $# -eq 0 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P
    elif [ $# -eq 1 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color $1
    else
        echo "Usage: listening [pattern]"
    fi
}

clone() {
  cd ~/work/repos
  url=$(osascript -e 'tell application "Brave" to return URL of active tab of front window')
  repo=${url:19}
  name=${repo:t}
  git clone git@github.com:$repo && nvim $name
}

new_react() {
  cd ~/work
  projectName=$1
  echo $projectName
  npx create-react-app $projectName
  nvim $projectName
}


function nvims() {
  items=("default" "kickstart" "LazyVim")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim $@
}
