[metadata]
name = "alias"
description = "A channel to select from shell aliases"

[source]
command = "$SHELL -ic 'alias'"
output = "{split: :1}"

[preview]
command = "$SHELL -ic 'type {split: :1}'"

[ui.preview_panel]
size = 30
